image: golang:alpine

stages:
  - build


go_build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o goBOT main.go
    - tar -czf goBOT.tar.gz goBOT
  artifacts:
    paths:
      - goBOT.tar.gz